name: copinstar-farkle

services:
  client:
    build:
      context: ..
      dockerfile: ./docker/client.Dockerfile
    ports:
      - 50051:80
    restart: unless-stopped

  server:
    build:
      context: ..
      dockerfile: ./docker/server.Dockerfile
    volumes:
      - ./data:/app/data
    restart: unless-stopped
